CREATE DATABASE IF NOT EXISTS saas_auth;
CREATE DATABASE IF NOT EXISTS saas_tenant;
CREATE DATABASE IF NOT EXISTS saas_billing;
CREATE DATABASE IF NOT EXISTS saas_payment;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;
